services:
 django-web:
   build: .
   container_name: django-docker
   volumes:
    - .:/app
   environment:
     DJANGO_SUPERUSER_USERNAME: admin
     DJANGO_SUPERUSER_EMAIL: admin@example.com
     DJANGO_SUPERUSER_PASSWORD: "admin"
     ASSINATURAS_PATH: /tmp/assinaturas
   command: >
          sh -c "
          python manage.py migrate --noinput &&
          python manage.py runserver 0.0.0.0:8000
          "
   ports:
     - "8000:8000"

