# Generated by Django 4.1.2 on 2024-05-30 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='depth',
            field=models.IntegerField(default=0),
        ),
    ]
