# Generated by Django 4.1.2 on 2024-05-30 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0002_categoria_depth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='is_active',
            new_name='categoria_ativa',
        ),
        migrations.RenameField(
            model_name='categoria',
            old_name='name',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='categoria',
            old_name='parent',
            new_name='parente',
        ),
        migrations.RenameField(
            model_name='categoria',
            old_name='depth',
            new_name='profundidade',
        ),
    ]
