# Generated by Django 4.1.2 on 2024-06-06 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0004_remove_categoria_profundidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='icone',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('arquivo', models.FileField(upload_to='documentos')),
                ('link', models.URLField(blank=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documentos.categoria')),
            ],
        ),
    ]
