# Generated by Django 4.1.2 on 2024-06-13 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0005_categoria_icone_documento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='link',
        ),
    ]
