# Generated by Django 4.1.1 on 2022-10-27 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_contato_ativo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contato',
            old_name='ativo',
            new_name='ramal_ativo',
        ),
        migrations.AddField(
            model_name='contato',
            name='nascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contato',
            name='pessoa_ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='contato',
            name='email',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='contato',
            name='funcao',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='contato',
            name='ramal',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='contato',
            name='telefone',
            field=models.CharField(default='-', max_length=16),
        ),
    ]
