# Generated by Django 4.1.2 on 2024-06-06 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0007_alter_contato_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='admissao',
            field=models.DateField(blank=True, null=True),
        ),
    ]
