# Generated by Django 4.1.2 on 2024-06-06 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0008_contato_admissao'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_funcionarios/'),
        ),
    ]
