# Generated by Django 4.1.2 on 2024-06-06 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0009_contato_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='image',
            field=models.ImageField(blank=True, default='media/fotos_funcionarios/placeholder.jpg', null=True, upload_to='fotos_funcionarios/'),
        ),
    ]
