# Generated by Django 4.1.2 on 2024-06-07 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0010_alter_contato_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_funcionarios/'),
        ),
    ]
