# Generated by Django 4.1.13 on 2025-04-25 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0011_alter_contato_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='funcao',
            options={'verbose_name': 'Função', 'verbose_name_plural': 'Funções'},
        ),
    ]
