# Generated by Django 4.1.13 on 2025-04-25 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grupos_familiares', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupofamiliar',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='grupofamiliar',
            name='tecnico',
        ),
    ]
