# Generated by Django 4.1.1 on 2022-10-06 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Agenda',
            new_name='Contato',
        ),
    ]
