# Generated by Django 4.1.2 on 2022-11-09 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recados', '0002_recado_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recado',
            name='texto',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='recado',
            name='titulo',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
