# Generated by Django 4.1.2 on 2024-06-10 16:53

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recados', '0003_alter_recado_texto_alter_recado_titulo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recado',
            name='image',
        ),
        migrations.AlterField(
            model_name='recado',
            name='texto',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
    ]
