# Generated by Django 4.1.2 on 2024-06-11 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recados', '0004_remove_recado_image_alter_recado_texto'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagemRecado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.AlterField(
            model_name='recado',
            name='texto',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='recado',
            name='image',
            field=models.ManyToManyField(to='recados.imagemrecado'),
        ),
    ]
