# Generated by Django 4.1.2 on 2024-06-11 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recados', '0006_remove_recado_image_recado_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recado',
            name='image',
        ),
        migrations.AddField(
            model_name='imagemrecado',
            name='recado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='recados.recado'),
        ),
    ]
