# Generated by Django 4.1.2 on 2024-06-12 20:41

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recados', '0007_remove_recado_image_imagemrecado_recado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemrecado',
            name='image',
            field=models.ImageField(default='', upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='imagemrecado',
            name='recado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recados.recado'),
        ),
        migrations.AlterField(
            model_name='recado',
            name='texto',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
