# Generated by Django 4.1.2 on 2024-06-13 17:03

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recados', '0008_alter_imagemrecado_image_alter_imagemrecado_recado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recado',
            name='texto',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recado',
            name='titulo',
            field=models.CharField(blank=True, max_length=104),
        ),
    ]
