# Generated by Django 4.1.2 on 2024-06-02 22:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_banner_titulo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Evento 2024-06-02 22:09:47.736311+00:00', max_length=100)),
                ('local', models.CharField(default='Local 2024-06-02 22:09:47.736311+00:00', max_length=100)),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterField(
            model_name='banner',
            name='titulo',
            field=models.CharField(default='Banner 2024-06-02 22:09:47.736311+00:00', max_length=100),
        ),
    ]
