# Generated by Django 4.1.2 on 2024-06-02 22:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_evento_alter_banner_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='titulo',
            field=models.CharField(default='Banner 2024-06-02 22:19:44.377432+00:00', max_length=100),
        ),
        migrations.AlterField(
            model_name='evento',
            name='data',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='evento',
            name='local',
            field=models.CharField(default='Local 2024-06-02 22:19:44.377432+00:00', max_length=100),
        ),
        migrations.AlterField(
            model_name='evento',
            name='titulo',
            field=models.CharField(default='Evento 2024-06-02 22:19:44.377432+00:00', max_length=100),
        ),
    ]
